### ISSUE TITLE
Fix intermittent test failures

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/Polykey-CLI#201]
### Specification

We need to look into and resolve any intermittent test failures in the tests. Any test failures found through local testing or in CI should be added to the list here.

### Tasks

1. Find any intermittent test failures.
2. Fix these test failues.

**Comment by brynblack** [comment]
Polykey-CLI failing due to timeout exceeding limit in `tests/agent/` for file `stop.test.ts`:
https://github.com/MatrixAI/Polykey-CLI/actions/runs/9689881030/job/26738839007

**Comment by brynblack** [comment]
```
FAIL tests/secrets/create.test.ts (26.826 s)
  commandCreateSecret
    ✓ should create secrets (8447 ms)
    ✕ secrets handle unix style paths for secrets (with seed=1689253545) (15620 ms)

  ● commandCreateSecret › secrets handle unix style paths for secrets (with seed=1689253545)

    Property failed after 3 tests
    { seed: 1689253545, path: "2:0", endOnFailure: true }
    Counterexample: [" ","=",""]
    Shrunk 1 time(s)
    Got error: expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 64

      107 |         cwd: dataDir,
      108 |       });
    > 109 |       expect(result.exitCode).toBe(0);
          |                               ^
      110 |
      111 |       await polykeyAgent.vaultManager.withVaults([vaultId], async (vault) => {
      112 |         const list = await vaultOps.listSecrets(vault);

      at toBe (tests/secrets/create.test.ts:109:31)
      at AsyncProperty.run (node_modules/fast-check/lib/check/property/AsyncProperty.generic.js:49:28)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:131:15)
      at asyncThrowIfFailed (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:148:11)
```

**Comment by CMCDragonkai** [comment]
This is insufficient detail. Each intermittent error should be identified as a separate issue (or group of issues). Also that recent error that @brynblack reported should be obviated by https://github.com/MatrixAI/Polykey-CLI/issues/32.
